### PR TITLE
feat: Provide capability to use serviceAccountName

### LINKED ISSUE #86: Provide capability to use serviceAccountName
### Proposal

Add the possibility to specify a serviceAccountName which is used to run the pods

### Use-Case

We are trying to run the api-management-self-hosted-gateway on Openshift 4.x, to be able to add a securitycontext to run as user 1001 we need to create a new serviceAccount with a non default SCC (https://docs.openshift.com/container-platform/4.8/authentication/managing-security-context-constraints.html) and use this serviceAccount for deployment.

This is related to https://github.com/Azure/api-management-self-hosted-gateway/issues/85

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by LDL-GH**
closes #86

### CODE REVIEW

**Review by tomkerkhove — APPROVED** [review]
Thanks!

**Comment by tomkerkhove** [comment]
Can you sign the CLA please?

**Comment by LDL-GH** [comment]
I wasn't aware there would be a CLA.
Since it claims I would represent the company while signing I need to send this up the chain of command (which may take a while) to get approval if I get any.
I was planning on making PRs for the other 2 issues as well, but that won't happen any time soon I'm afraid.

**Comment by tomkerkhove** [comment]
No problem at all and take the time that you need. Thanks for checking.

**Comment by LDL-GH** [comment]
@tomkerkhove CLA is signed. I'll be looking at the other two issues soon

**Comment by tomkerkhove** [comment]
Awesome, thank you!

**Pull request merged**
