### PR TITLE
feat: Add support for `ingressClassName` in ingress

### PR DESCRIPTION
**Pull request by TimMnz09**
This pull-request implements a solution for #177
The changes have been tested locally

### CODE REVIEW

**Comment by TimMnz09** [comment]
@microsoft-github-policy-service agree

**Review by tomkerkhove — APPROVED** [review]

**Comment by TimMnz09** [comment]
@tomkerkhove seems like there is an issue with the authentication at azure api. 
Can you have a look at this? It does not seem to be related to my commit.

**Comment by tomkerkhove** [comment]
Sorry, I forgot to follow-up on this PR. It's fine, it's just regular GH + secrets pain.

**Comment by tomkerkhove** [comment]
Thank you for your contribution!

**Pull request merged**
