### PR TITLE
feat: Provide support for configuring hostAliases

### PR DESCRIPTION
**Pull request by RomanDvorsky**
The configuration URL is not added to the public DNS in case the APIM is in VNET. 
This way you can specify given configuration URL and it's IP directly to the APIM deployment.

### CODE REVIEW

**Review by tomkerkhove — COMMENTED** [review]
Great idea, thank you! Would you mind updating the README with the new setting please?

One suggestion would be to use `gateway.deployment.dns.hostAliases` in case we need to expose more DNS knobs in the future

**Comment by oskrabanek** [comment]
> Great idea, thank you! Would you mind updating the README with the new setting please?
> 
> One suggestion would be to use `gateway.deployment.dns.hostAliases` in case we need to expose more DNS knobs in the future

Are you sure with the naming? In V2 all configs prefixed `gateway` have been replaced with `config`
Source: https://learn.microsoft.com/en-us/azure/api-management/self-hosted-gateway-settings-reference

**Comment by tomkerkhove** [comment]
@oskrabanek You are looking at the container reference, not Helm chart reference.

You can find all the Helm chart configuration here: https://github.com/Azure/api-management-self-hosted-gateway/tree/main/helm-charts/azure-api-management-gateway#configuration

**Comment by RomanDvorsky** [comment]
> Great idea, thank you! Would you mind updating the README with the new setting please?
> 
> One suggestion would be to use `gateway.deployment.dns.hostAliases` in case we need to expose more DNS knobs in the future

Hi, added readme and moved to `dns` node, not sure whether the reference to `values.yaml` file is ok or how to specify the details of `hostAliases` configuration...

**Review by tomkerkhove — APPROVED** [review]
LGTM, that should be fine - Thanks!

**Comment by tomkerkhove** [comment]
> @RomanDvorsky please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> 
> Contributor License Agreement

@RomanDvorsky Would you mind agreeing with the CLA please?

**Comment by RomanDvorsky** [comment]
> 

Hi, you mean something like:

@microsoft-github-policy-service agree [company="Oriflame"]

of course I do agree with CLA ;)

**Comment by RomanDvorsky** [comment]
> Thank you for the contribution!

You are welcomed ;) any idea when it is going to be published? the package 1.5.2 is already out but I guess without this change...

**Comment by tomkerkhove** [comment]
Here you go: https://github.com/Azure/api-management-self-hosted-gateway/releases/tag/v1.5.3

**Comment by RomanDvorsky** [comment]
> Here you go: https://github.com/Azure/api-management-self-hosted-gateway/releases/tag/v1.5.3

thx a lot - our self hosted gw is running without manual tweaks and workarounds! ;)

**Comment by tomkerkhove** [comment]
Lovely! Thanks for the contribution and using our self-hosted gateway.

**Pull request merged**
