### PR TITLE
Provide capability to opt-in for Dapr integration

### PR DESCRIPTION
**Pull request by tomkerkhove**
Signed-off-by: Tom Kerkhove <kerkhove.tom@gmail.com>

Standard approach:
```shell
> helm template .\azure-api-management-gateway\
...
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME-azure-api-management-gateway
  labels:
    app.kubernetes.io/name: azure-api-management-gateway
    helm.sh/chart: azure-api-management-gateway-0.2.0
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: azure-api-management-gateway
      app.kubernetes.io/instance: RELEASE-NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: azure-api-management-gateway
        app.kubernetes.io/instance: RELEASE-NAME
    spec:
      containers:
        - name: azure-api-management-gateway
          image: "mcr.microsoft.com/azure-api-management/gateway:latest"
...
```

With opt-in for Dapr integration:

```shell
> helm template .\azure-api-management-gateway\ --set dapr.appId=hello --set dapr.enabled=true
...
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME-azure-api-management-gateway
  labels:
    app.kubernetes.io/name: azure-api-management-gateway
    helm.sh/chart: azure-api-management-gateway-0.2.0
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: azure-api-management-gateway
      app.kubernetes.io/instance: RELEASE-NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: azure-api-management-gateway
        app.kubernetes.io/instance: RELEASE-NAME
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "hello"
    spec:
      containers:
        - name: azure-api-management-gateway
          image: "mcr.microsoft.com/azure-api-management/gateway:latest"
...
```

/cc @vladvino @mchmarny

### CODE REVIEW

**Comment by tomkerkhove** [comment]
@mchmarny I haven't tested this with Dapr itself, would you mind giving this a go please?

**Comment by mchmarny** [comment]
Sorry I missed that... my GH notifications don't work unless I'm logged into the MS SSO. Will do

**Comment by mchmarny** [comment]
LGTM, thanks for doing it. Any chance to enable the 3 other common annotations? 

```yaml
        dapr.io/config: "tracing"
        dapr.io/log-as-json: "true"
        dapr.io/log-level: "debug"
```

**Comment by tomkerkhove** [comment]
I certainly can! Should I use these values as defaults?

**Comment by mchmarny** [comment]
No, let's keep it simple by defaults. Otherwise LGTM. Thanks!

**Comment by tomkerkhove** [comment]
Updated, feel free to give it a go:
```yaml
metadata:
      labels:
        app.kubernetes.io/name: azure-api-management-gateway
        app.kubernetes.io/instance: RELEASE-NAME
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "hello"
        dapr.io/config: "tracing"
        dapr.io/log-as-json: "true"
        dapr.io/log-level: "info"
```

**Comment by mchmarny** [comment]
lgtm, will update the demo when this lands

**Comment by tomkerkhove** [comment]
Only need @vladvino his sign-off!

**Comment by vladvino** [comment]
Done, thank you!
________________________________

**Comment by tomkerkhove** [comment]
Happy to help!

**Pull request merged**
