### PR TITLE
feat: Provide capability to use SecurityContext

### LINKED ISSUE #85: Provide capability to add security context configuration
### Proposal

The Securitycontext should be set by default or be configurable in the helm chart.

### Use-Case

According to following issue we should configure the securitycontext to be able to run the Api management self hosted gateway:
https://github.com/Azure/api-management-self-hosted-gateway/issues/82

Using the helm chart this does not seem possible right now

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by LDL-GH**
closes #85 
Signed-off-by: Laurens Peeters <laurens.peeters@delijn.be>

### CODE REVIEW

**Review by tomkerkhove — APPROVED** [review]
LGTM, but can you remove the new version please?

**Comment by LDL-GH** [comment]
My bad, should be ok now

**Comment by tomkerkhove** [comment]
Thanks! Glad to se contributions from a Belgian 😉

**Comment by LDL-GH** [comment]
We do our best right? 😄

**Pull request merged**
